services:
  - type: web
    name: discord-advanced-bot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CALLBACK_URL
        sync: false
      - key: GUILD_ID
        sync: false
      - key: PREFIX
        value: "!"
      - key: FEATURE_AUTOMOD
        value: "true"
      - key: FEATURE_VOICE_RECORDING
        value: "true"
      - key: FEATURE_LIVE_NOTIFICATION
        value: "true"
      - key: FEATURE_DASHBOARD
        value: "true"
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
